-- ============================================
-- Sistema de amigos, tags, desafíos entre amigos y logros 365 días
-- ============================================

-- Agregar username y tag a users
ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS tag VARCHAR(10);

-- Tabla de amigos (solicitudes + aceptadas)
CREATE TABLE IF NOT EXISTS friends (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  friend_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'blocked')),
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, friend_id),
  CHECK (user_id != friend_id)
);

CREATE INDEX IF NOT EXISTS idx_friends_user ON friends(user_id);
CREATE INDEX IF NOT EXISTS idx_friends_friend ON friends(friend_id);
CREATE INDEX IF NOT EXISTS idx_friends_status ON friends(status);

-- Tabla de desafíos entre amigos
CREATE TABLE IF NOT EXISTS friend_challenges (
  id SERIAL PRIMARY KEY,
  challenger_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  challenged_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  challenge_id INTEGER REFERENCES challenges(id) ON DELETE SET NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  points_wagered INTEGER DEFAULT 50,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'completed', 'expired')),
  winner_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  challenger_completed BOOLEAN DEFAULT FALSE,
  challenged_completed BOOLEAN DEFAULT FALSE,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fc_challenger ON friend_challenges(challenger_id);
CREATE INDEX IF NOT EXISTS idx_fc_challenged ON friend_challenges(challenged_id);
CREATE INDEX IF NOT EXISTS idx_fc_status ON friend_challenges(status);
CREATE INDEX IF NOT EXISTS idx_fc_expires ON friend_challenges(expires_at);

-- Tabla de logros diarios (365 días)
CREATE TABLE IF NOT EXISTS daily_achievements (
  id SERIAL PRIMARY KEY,
  day_of_year INTEGER UNIQUE NOT NULL CHECK (day_of_year BETWEEN 1 AND 365),
  name VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  icon VARCHAR(50) DEFAULT 'IconCalendarStar',
  color VARCHAR(7) DEFAULT '#7C3AED',
  created_at TIMESTAMP DEFAULT NOW()
);

-- Tabla de logros desbloqueados por usuario
CREATE TABLE IF NOT EXISTS user_daily_achievements (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  achievement_day INTEGER NOT NULL CHECK (achievement_day BETWEEN 1 AND 365),
  unlocked_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, achievement_day)
);

CREATE INDEX IF NOT EXISTS idx_uda_user ON user_daily_achievements(user_id);

-- Poblar 365 logros diarios
INSERT INTO daily_achievements (day_of_year, name, description, icon, color) VALUES
  (1, 'Primero del año', 'Desbloquea tu primer logro del año', 'IconTrophy', '#F59E0B'),
  (2, 'Constancia', 'Mantén tu racha por 2 días', 'IconFlame', '#EF4444'),
  (3, 'Triángulo perfecto', 'Completa 3 hábitos en un día', 'IconTriangle', '#3B82F6'),
  (4, 'Cuatro estrellas', 'Alcanza nivel 4', 'IconStar', '#FBBF24'),
  (5, 'Cinco días seguidos', '5 días de racha consecutiva', 'IconFlame', '#EF4444'),
  (6, 'Media docena', 'Completa 6 hábitos en total', 'IconCheck', '#2ECC71'),
  (7, 'Semana completa', '7 días de racha', 'IconCalendarWeek', '#7C3AED'),
  (8, 'Superando límites', 'Completa 8 hábitos en un día', 'IconRocket', '#8B5CF6'),
  (9, 'Nueve vidas', 'Reinicia tu racha 9 veces y sigue adelante', 'IconHeart', '#EC4899'),
  (10, 'Doble dígito', 'Alcanza nivel 10', 'IconCrown', '#FBBF24'),
  (11, 'Once y counting', '11 días de racha', 'IconCalendar', '#3B82F6'),
  (12, 'Docena perfecta', 'Completa 12 hábitos en un día', 'IconCheck', '#2ECC71'),
  (13, 'Malo no es malo', 'Supera el día 13 con racha', 'IconMoodSmile', '#10B981'),
  (14, 'Dos semanas', '14 días de racha consecutiva', 'IconCalendarWeek', '#7C3AED'),
  (15, 'Quinceañero', 'Alcanza 15 niveles', 'IconTrophy', '#F59E0B'),
  (16, 'Dieciséis bits', 'Completa 16 hábitos en total', 'IconTarget', '#EF4444'),
  (17, 'Diecisiete días', '17 días de racha', 'IconFlame', '#EF4444'),
  (18, 'Mayoría activa', '18 días de actividad', 'IconUser', '#3B82F6'),
  (19, 'Diecinueve puntos', 'Acumula 190 puntos', 'IconCoin', '#FBBF24'),
  (20, 'Veinte niveles', 'Alcanza nivel 20', 'IconCrown', '#FBBF24'),
  (21, 'Tres semanas', '21 días de racha', 'IconCalendarWeek', '#7C3AED'),
  (22, 'Ventidós hábitos', 'Completa 22 hábitos en total', 'IconTarget', '#EF4444'),
  (23, 'Veintitrés', '23 días de actividad', 'IconCalendar', '#3B82F6'),
  (24, 'Veinticuatro horas', 'Completa un hábito cada hora del día', 'IconClock', '#8B5CF6'),
  (25, 'Un cuarto de siglo', '25 días de racha', 'IconFlame', '#EF4444'),
  (26, 'Veintiséis', 'Alcanza nivel 26', 'IconCrown', '#FBBF24'),
  (27, 'Veintisiete puntos', 'Acumula 270 puntos', 'IconCoin', '#FBBF24'),
  (28, 'Veintiocho días', '28 días de racha (casi un mes)', 'IconCalendarMonth', '#7C3AED'),
  (29, 'Veintinueve hábitos', 'Completa 29 hábitos en total', 'IconTarget', '#EF4444'),
  (30, 'Un mes completo', '30 días de racha', 'IconCalendarMonth', '#7C3AED'),
  (31, 'Treinta y uno', '31 días de actividad constante', 'IconCalendar', '#3B82F6'),
  (32, 'Treinta y dos', 'Alcanza nivel 32', 'IconCrown', '#FBBF24'),
  (33, 'Treinta y tres', '33 días de racha', 'IconFlame', '#EF4444'),
  (34, 'Treinta y cuatro', 'Completa 34 hábitos en total', 'IconTarget', '#EF4444'),
  (35, 'Cinco semanas', '35 días de racha', 'IconCalendarWeek', '#7C3AED'),
  (36, 'Treinta y seis', 'Acumula 360 puntos', 'IconCoin', '#FBBF24'),
  (37, 'Treinta y siete', '37 días de actividad', 'IconCalendar', '#3B82F6'),
  (38, 'Treinta y ocho', 'Alcanza nivel 38', 'IconCrown', '#FBBF24'),
  (39, 'Treinta y nueve', '39 días de racha', 'IconFlame', '#EF4444'),
  (40, 'Cuarenta', '40 días de racha consecutiva', 'IconFlame', '#EF4444'),
  (41, 'Cuarenta y uno', '41 días de actividad', 'IconCalendar', '#3B82F6'),
  (42, 'La respuesta', '42 días — la respuesta a todo', 'IconSparkles', '#8B5CF6'),
  (43, 'Cuarenta y tres', 'Alcanza nivel 43', 'IconCrown', '#FBBF24'),
  (44, 'Cuarenta y cuatro', '44 días de racha', 'IconFlame', '#EF4444'),
  (45, 'Cuarenta y cinco', 'Completa 45 hábitos en total', 'IconTarget', '#EF4444'),
  (46, 'Cuarenta y seis', 'Acumula 460 puntos', 'IconCoin', '#FBBF24'),
  (47, 'Cuarenta y siete', '47 días de actividad', 'IconCalendar', '#3B82F6'),
  (48, 'Cuarenta y ocho', '48 días de racha', 'IconFlame', '#EF4444'),
  (49, 'Siete semanas', '49 días de racha (7 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (50, 'Cincuenta', '50 días de racha consecutiva', 'IconFlame', '#EF4444'),
  (51, 'Cincuenta y uno', 'Alcanza nivel 51', 'IconCrown', '#FBBF24'),
  (52, 'Cincuenta y dos', '52 días de actividad (un año de semanas)', 'IconCalendar', '#3B82F6'),
  (53, 'Cincuenta y tres', '53 días de racha', 'IconFlame', '#EF4444'),
  (54, 'Cincuenta y cuatro', 'Completa 54 hábitos en total', 'IconTarget', '#EF4444'),
  (55, 'Cincuenta y cinco', 'Acumula 550 puntos', 'IconCoin', '#FBBF24'),
  (56, 'Ocho semanas', '56 días de racha (8 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (57, 'Cincuenta y siete', '57 días de actividad', 'IconCalendar', '#3B82F6'),
  (58, 'Cincuenta y ocho', 'Alcanza nivel 58', 'IconCrown', '#FBBF24'),
  (59, 'Cincuenta y nueve', '59 días de racha', 'IconFlame', '#EF4444'),
  (60, 'Dos meses', '60 días de racha consecutiva', 'IconCalendarMonth', '#7C3AED'),
  (61, 'Sesenta y uno', '61 días de actividad', 'IconCalendar', '#3B82F6'),
  (62, 'Sesenta y dos', 'Completa 62 hábitos en total', 'IconTarget', '#EF4444'),
  (63, 'Nueve semanas', '63 días de racha (9 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (64, 'Sesenta y cuatro', 'Alcanza nivel 64', 'IconCrown', '#FBBF24'),
  (65, 'Sesenta y cinco', 'Acumula 650 puntos', 'IconCoin', '#FBBF24'),
  (66, 'Sesenta y seis', '66 días de racha', 'IconFlame', '#EF4444'),
  (67, 'Sesenta y siete', '67 días de actividad', 'IconCalendar', '#3B82F6'),
  (68, 'Sesenta y ocho', 'Completa 68 hábitos en total', 'IconTarget', '#EF4444'),
  (69, 'Sesenta y nueve', '69 días de racha', 'IconFlame', '#EF4444'),
  (70, 'Diez semanas', '70 días de racha (10 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (71, 'Setenta y uno', 'Alcanza nivel 71', 'IconCrown', '#FBBF24'),
  (72, 'Setenta y dos', '72 días de actividad', 'IconCalendar', '#3B82F6'),
  (73, 'Setenta y tres', 'Acumula 730 puntos', 'IconCoin', '#FBBF24'),
  (74, 'Setenta y cuatro', '74 días de racha', 'IconFlame', '#EF4444'),
  (75, 'Setenta y cinco', '75 días de racha (2.5 meses)', 'IconCalendarMonth', '#7C3AED'),
  (76, 'Setenta y seis', 'Completa 76 hábitos en total', 'IconTarget', '#EF4444'),
  (77, 'Setenta y siete', '77 días de actividad', 'IconCalendar', '#3B82F6'),
  (78, 'Setenta y ocho', 'Alcanza nivel 78', 'IconCrown', '#FBBF24'),
  (79, 'Setenta y nueve', '79 días de racha', 'IconFlame', '#EF4444'),
  (80, 'Ochenta', '80 días de racha consecutiva', 'IconFlame', '#EF4444'),
  (81, 'Ochenta y uno', '81 días de actividad', 'IconCalendar', '#3B82F6'),
  (82, 'Ochenta y dos', 'Acumula 820 puntos', 'IconCoin', '#FBBF24'),
  (83, 'Ochenta y tres', '83 días de racha', 'IconFlame', '#EF4444'),
  (84, 'Doce semanas', '84 días de racha (12 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (85, 'Ochenta y cinco', 'Completa 85 hábitos en total', 'IconTarget', '#EF4444'),
  (86, 'Ochenta y seis', 'Alcanza nivel 86', 'IconCrown', '#FBBF24'),
  (87, 'Ochenta y siete', '87 días de actividad', 'IconCalendar', '#3B82F6'),
  (88, 'Ochenta y ocho', '88 días de racha', 'IconFlame', '#EF4444'),
  (89, 'Ochenta y nueve', 'Acumula 890 puntos', 'IconCoin', '#FBBF24'),
  (90, 'Tres meses', '90 días de racha (3 meses)', 'IconCalendarMonth', '#7C3AED'),
  (91, 'Noventa y uno', '91 días de actividad', 'IconCalendar', '#3B82F6'),
  (92, 'Noventa y dos', 'Completa 92 hábitos en total', 'IconTarget', '#EF4444'),
  (93, 'Noventa y tres', '93 días de racha', 'IconFlame', '#EF4444'),
  (94, 'Noventa y cuatro', 'Alcanza nivel 94', 'IconCrown', '#FBBF24'),
  (95, 'Noventa y cinco', '95 días de actividad', 'IconCalendar', '#3B82F6'),
  (96, 'Noventa y seis', '96 días de racha', 'IconFlame', '#EF4444'),
  (97, 'Noventa y siete', 'Acumula 970 puntos', 'IconCoin', '#FBBF24'),
  (98, 'Noventa y ocho', '98 días de actividad', 'IconCalendar', '#3B82F6'),
  (99, 'Noventa y nueve', '99 días de racha', 'IconFlame', '#EF4444'),
  (100, '¡Cien!', '100 días de racha consecutiva', 'IconTrophy', '#F59E0B'),
  (101, 'Ciento uno', '101 días de actividad', 'IconCalendar', '#3B82F6'),
  (102, 'Ciento dos', 'Completa 102 hábitos en total', 'IconTarget', '#EF4444'),
  (103, 'Ciento tres', '103 días de racha', 'IconFlame', '#EF4444'),
  (104, 'Catorce semanas', '104 días de racha (14 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (105, 'Ciento cinco', 'Alcanza nivel 105', 'IconCrown', '#FBBF24'),
  (106, 'Ciento seis', '106 días de actividad', 'IconCalendar', '#3B82F6'),
  (107, 'Ciento siete', 'Acumula 1070 puntos', 'IconCoin', '#FBBF24'),
  (108, 'Ciento ocho', '108 días de racha', 'IconFlame', '#EF4444'),
  (109, 'Ciento nueve', '109 días de actividad', 'IconCalendar', '#3B82F6'),
  (110, 'Ciento diez', '110 días de racha', 'IconFlame', '#EF4444'),
  (111, 'Ciento once', '111 días de actividad', 'IconCalendar', '#3B82F6'),
  (112, 'Ciento doce', 'Completa 112 hábitos en total', 'IconTarget', '#EF4444'),
  (113, 'Ciento trece', '113 días de racha', 'IconFlame', '#EF4444'),
  (114, 'Ciento catorce', 'Alcanza nivel 114', 'IconCrown', '#FBBF24'),
  (115, 'Ciento quince', '115 días de actividad', 'IconCalendar', '#3B82F6'),
  (116, 'Ciento dieciséis', '116 días de racha', 'IconFlame', '#EF4444'),
  (117, 'Ciento diecisiete', 'Acumula 1170 puntos', 'IconCoin', '#FBBF24'),
  (118, 'Ciento dieciocho', '118 días de actividad', 'IconCalendar', '#3B82F6'),
  (119, 'Ciento diecinueve', '119 días de racha', 'IconFlame', '#EF4444'),
  (120, 'Cuatro meses', '120 días de racha (4 meses)', 'IconCalendarMonth', '#7C3AED'),
  (121, 'Ciento veintiuno', '121 días de actividad', 'IconCalendar', '#3B82F6'),
  (122, 'Ciento veintidós', 'Completa 122 hábitos en total', 'IconTarget', '#EF4444'),
  (123, 'Ciento veintitrés', '123 días de racha', 'IconFlame', '#EF4444'),
  (124, 'Ciento veinticuatro', 'Alcanza nivel 124', 'IconCrown', '#FBBF24'),
  (125, 'Ciento veinticinco', '125 días de actividad', 'IconCalendar', '#3B82F6'),
  (126, 'Ciento veintiséis', '126 días de racha (18 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (127, 'Ciento veintisiete', 'Acumula 1270 puntos', 'IconCoin', '#FBBF24'),
  (128, 'Ciento veintiocho', '128 días de actividad', 'IconCalendar', '#3B82F6'),
  (129, 'Ciento veintinueve', '129 días de racha', 'IconFlame', '#EF4444'),
  (130, 'Ciento treinta', '130 días de actividad', 'IconCalendar', '#3B82F6'),
  (131, 'Ciento treinta y uno', '131 días de racha', 'IconFlame', '#EF4444'),
  (132, 'Ciento treinta y dos', 'Completa 132 hábitos en total', 'IconTarget', '#EF4444'),
  (133, 'Ciento treinta y tres', '133 días de actividad', 'IconCalendar', '#3B82F6'),
  (134, 'Ciento treinta y cuatro', 'Alcanza nivel 134', 'IconCrown', '#FBBF24'),
  (135, 'Ciento treinta y cinco', '135 días de racha (4.5 meses)', 'IconCalendarMonth', '#7C3AED'),
  (136, 'Ciento treinta y seis', '136 días de actividad', 'IconCalendar', '#3B82F6'),
  (137, 'Ciento treinta y siete', 'Acumula 1370 puntos', 'IconCoin', '#FBBF24'),
  (138, 'Ciento treinta y ocho', '138 días de racha', 'IconFlame', '#EF4444'),
  (139, 'Ciento treinta y nueve', '139 días de actividad', 'IconCalendar', '#3B82F6'),
  (140, 'Ciento cuarenta', '140 días de racha (20 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (141, 'Ciento cuarenta y uno', '141 días de actividad', 'IconCalendar', '#3B82F6'),
  (142, 'Ciento cuarenta y dos', 'Completa 142 hábitos en total', 'IconTarget', '#EF4444'),
  (143, 'Ciento cuarenta y tres', '143 días de racha', 'IconFlame', '#EF4444'),
  (144, 'Ciento cuarenta y cuatro', 'Alcanza nivel 144', 'IconCrown', '#FBBF24'),
  (145, 'Ciento cuarenta y cinco', '145 días de actividad', 'IconCalendar', '#3B82F6'),
  (146, 'Ciento cuarenta y seis', '146 días de racha', 'IconFlame', '#EF4444'),
  (147, 'Ciento cuarenta y siete', 'Acumula 1470 puntos', 'IconCoin', '#FBBF24'),
  (148, 'Ciento cuarenta y ocho', '148 días de actividad', 'IconCalendar', '#3B82F6'),
  (149, 'Ciento cuarenta y nueve', '149 días de racha', 'IconFlame', '#EF4444'),
  (150, 'Ciento cincuenta', '150 días de racha (5 meses)', 'IconCalendarMonth', '#7C3AED'),
  (151, 'Ciento cincuenta y uno', '151 días de actividad', 'IconCalendar', '#3B82F6'),
  (152, 'Ciento cincuenta y dos', 'Completa 152 hábitos en total', 'IconTarget', '#EF4444'),
  (153, 'Ciento cincuenta y tres', '153 días de racha', 'IconFlame', '#EF4444'),
  (154, 'Ciento cincuenta y cuatro', 'Alcanza nivel 154', 'IconCrown', '#FBBF24'),
  (155, 'Ciento cincuenta y cinco', '155 días de actividad', 'IconCalendar', '#3B82F6'),
  (156, 'Ciento cincuenta y seis', '156 días de racha (22 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (157, 'Ciento cincuenta y siete', 'Acumula 1570 puntos', 'IconCoin', '#FBBF24'),
  (158, 'Ciento cincuenta y ocho', '158 días de actividad', 'IconCalendar', '#3B82F6'),
  (159, 'Ciento cincuenta y nueve', '159 días de racha', 'IconFlame', '#EF4444'),
  (160, 'Ciento sesenta', '160 días de actividad', 'IconCalendar', '#3B82F6'),
  (161, 'Ciento sesenta y uno', '161 días de racha', 'IconFlame', '#EF4444'),
  (162, 'Ciento sesenta y dos', 'Completa 162 hábitos en total', 'IconTarget', '#EF4444'),
  (163, 'Ciento sesenta y tres', '163 días de actividad', 'IconCalendar', '#3B82F6'),
  (164, 'Ciento sesenta y cuatro', 'Alcanza nivel 164', 'IconCrown', '#FBBF24'),
  (165, 'Ciento sesenta y cinco', '165 días de racha (5.5 meses)', 'IconCalendarMonth', '#7C3AED'),
  (166, 'Ciento sesenta y seis', '166 días de actividad', 'IconCalendar', '#3B82F6'),
  (167, 'Ciento sesenta y siete', 'Acumula 1670 puntos', 'IconCoin', '#FBBF24'),
  (168, 'Ciento sesenta y ocho', '168 días de racha (24 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (169, 'Ciento sesenta y nueve', '169 días de actividad', 'IconCalendar', '#3B82F6'),
  (170, 'Ciento setenta', '170 días de racha', 'IconFlame', '#EF4444'),
  (171, 'Ciento setenta y uno', '171 días de actividad', 'IconCalendar', '#3B82F6'),
  (172, 'Ciento setenta y dos', 'Completa 172 hábitos en total', 'IconTarget', '#EF4444'),
  (173, 'Ciento setenta y tres', '173 días de racha', 'IconFlame', '#EF4444'),
  (174, 'Ciento setenta y cuatro', 'Alcanza nivel 174', 'IconCrown', '#FBBF24'),
  (175, 'Ciento setenta y cinco', '175 días de actividad', 'IconCalendar', '#3B82F6'),
  (176, 'Ciento setenta y seis', '176 días de racha', 'IconFlame', '#EF4444'),
  (177, 'Ciento setenta y siete', 'Acumula 1770 puntos', 'IconCoin', '#FBBF24'),
  (178, 'Ciento setenta y ocho', '178 días de actividad', 'IconCalendar', '#3B82F6'),
  (179, 'Ciento setenta y nueve', '179 días de racha', 'IconFlame', '#EF4444'),
  (180, 'Seis meses', '180 días de racha (6 meses)', 'IconCalendarMonth', '#7C3AED'),
  (181, 'Ciento ochenta y uno', '181 días de actividad', 'IconCalendar', '#3B82F6'),
  (182, 'Ciento ochenta y dos', 'Completa 182 hábitos en total', 'IconTarget', '#EF4444'),
  (183, 'Ciento ochenta y tres', '183 días de racha', 'IconFlame', '#EF4444'),
  (184, 'Ciento ochenta y cuatro', 'Alcanza nivel 184', 'IconCrown', '#FBBF24'),
  (185, 'Ciento ochenta y cinco', '185 días de actividad', 'IconCalendar', '#3B82F6'),
  (186, 'Ciento ochenta y seis', '186 días de racha (26.5 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (187, 'Ciento ochenta y siete', 'Acumula 1870 puntos', 'IconCoin', '#FBBF24'),
  (188, 'Ciento ochenta y ocho', '188 días de actividad', 'IconCalendar', '#3B82F6'),
  (189, 'Ciento ochenta y nueve', '189 días de racha', 'IconFlame', '#EF4444'),
  (190, 'Ciento noventa', '190 días de actividad', 'IconCalendar', '#3B82F6'),
  (191, 'Ciento noventa y uno', '191 días de racha', 'IconFlame', '#EF4444'),
  (192, 'Ciento noventa y dos', 'Completa 192 hábitos en total', 'IconTarget', '#EF4444'),
  (193, 'Ciento noventa y tres', '193 días de actividad', 'IconCalendar', '#3B82F6'),
  (194, 'Ciento noventa y cuatro', 'Alcanza nivel 194', 'IconCrown', '#FBBF24'),
  (195, 'Ciento noventa y cinco', '195 días de racha (6.5 meses)', 'IconCalendarMonth', '#7C3AED'),
  (196, 'Ciento noventa y seis', '196 días de actividad', 'IconCalendar', '#3B82F6'),
  (197, 'Ciento noventa y siete', 'Acumula 1970 puntos', 'IconCoin', '#FBBF24'),
  (198, 'Ciento noventa y ocho', '198 días de racha (28 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (199, 'Ciento noventa y nueve', '199 días de actividad', 'IconCalendar', '#3B82F6'),
  (200, '¡Doscientos!', '200 días de racha consecutiva', 'IconTrophy', '#F59E0B'),
  (201, 'Doscientos uno', '201 días de actividad', 'IconCalendar', '#3B82F6'),
  (202, 'Doscientos dos', 'Completa 202 hábitos en total', 'IconTarget', '#EF4444'),
  (203, 'Doscientos tres', '203 días de racha', 'IconFlame', '#EF4444'),
  (204, 'Doscientos cuatro', 'Alcanza nivel 204', 'IconCrown', '#FBBF24'),
  (205, 'Doscientos cinco', '205 días de actividad', 'IconCalendar', '#3B82F6'),
  (206, 'Doscientos seis', '206 días de racha', 'IconFlame', '#EF4444'),
  (207, 'Doscientos siete', 'Acumula 2070 puntos', 'IconCoin', '#FBBF24'),
  (208, 'Doscientos ocho', '208 días de actividad (29.5 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (209, 'Doscientos nueve', '209 días de racha', 'IconFlame', '#EF4444'),
  (210, 'Doscientos diez', '210 días de racha (7 meses)', 'IconCalendarMonth', '#7C3AED'),
  (211, 'Doscientos once', '211 días de actividad', 'IconCalendar', '#3B82F6'),
  (212, 'Doscientos doce', 'Completa 212 hábitos en total', 'IconTarget', '#EF4444'),
  (213, 'Doscientos trece', '213 días de racha', 'IconFlame', '#EF4444'),
  (214, 'Doscientos catorce', 'Alcanza nivel 214', 'IconCrown', '#FBBF24'),
  (215, 'Doscientos quince', '215 días de actividad', 'IconCalendar', '#3B82F6'),
  (216, 'Doscientos dieciséis', '216 días de racha (30.5 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (217, 'Doscientos diecisiete', 'Acumula 2170 puntos', 'IconCoin', '#FBBF24'),
  (218, 'Doscientos dieciocho', '218 días de actividad', 'IconCalendar', '#3B82F6'),
  (219, 'Doscientos diecinueve', '219 días de racha', 'IconFlame', '#EF4444'),
  (220, 'Doscientos veinte', '220 días de actividad', 'IconCalendar', '#3B82F6'),
  (221, 'Doscientos veintiuno', '221 días de racha', 'IconFlame', '#EF4444'),
  (222, 'Doscientos veintidós', 'Completa 222 hábitos en total', 'IconTarget', '#EF4444'),
  (223, 'Doscientos veintitrés', '223 días de actividad', 'IconCalendar', '#3B82F6'),
  (224, 'Doscientos veinticuatro', 'Alcanza nivel 224', 'IconCrown', '#FBBF24'),
  (225, 'Doscientos veinticinco', '225 días de racha (7.5 meses)', 'IconCalendarMonth', '#7C3AED'),
  (226, 'Doscientos veintiséis', '226 días de actividad', 'IconCalendar', '#3B82F6'),
  (227, 'Doscientos veintisiete', 'Acumula 2270 puntos', 'IconCoin', '#FBBF24'),
  (228, 'Doscientos veintiocho', '228 días de racha (32.5 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (229, 'Doscientos veintinueve', '229 días de actividad', 'IconCalendar', '#3B82F6'),
  (230, 'Doscientos treinta', '230 días de racha', 'IconFlame', '#EF4444'),
  (231, 'Doscientos treinta y uno', '231 días de actividad', 'IconCalendar', '#3B82F6'),
  (232, 'Doscientos treinta y dos', 'Completa 232 hábitos en total', 'IconTarget', '#EF4444'),
  (233, 'Doscientos treinta y tres', '233 días de racha', 'IconFlame', '#EF4444'),
  (234, 'Doscientos treinta y cuatro', 'Alcanza nivel 234', 'IconCrown', '#FBBF24'),
  (235, 'Doscientos treinta y cinco', '235 días de actividad', 'IconCalendar', '#3B82F6'),
  (236, 'Doscientos treinta y seis', '236 días de racha', 'IconFlame', '#EF4444'),
  (237, 'Doscientos treinta y siete', 'Acumula 2370 puntos', 'IconCoin', '#FBBF24'),
  (238, 'Doscientos treinta y ocho', '238 días de actividad', 'IconCalendar', '#3B82F6'),
  (239, 'Doscientos treinta y nueve', '239 días de racha', 'IconFlame', '#EF4444'),
  (240, 'Ocho meses', '240 días de racha (8 meses)', 'IconCalendarMonth', '#7C3AED'),
  (241, 'Doscientos cuarenta y uno', '241 días de actividad', 'IconCalendar', '#3B82F6'),
  (242, 'Doscientos cuarenta y dos', 'Completa 242 hábitos en total', 'IconTarget', '#EF4444'),
  (243, 'Doscientos cuarenta y tres', '243 días de racha', 'IconFlame', '#EF4444'),
  (244, 'Doscientos cuarenta y cuatro', 'Alcanza nivel 244', 'IconCrown', '#FBBF24'),
  (245, 'Doscientos cuarenta y cinco', '245 días de actividad', 'IconCalendar', '#3B82F6'),
  (246, 'Doscientos cuarenta y seis', '246 días de racha (35 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (247, 'Doscientos cuarenta y siete', 'Acumula 2470 puntos', 'IconCoin', '#FBBF24'),
  (248, 'Doscientos cuarenta y ocho', '248 días de actividad', 'IconCalendar', '#3B82F6'),
  (249, 'Doscientos cuarenta y nueve', '249 días de racha', 'IconFlame', '#EF4444'),
  (250, 'Doscientos cincuenta', '250 días de racha', 'IconFlame', '#EF4444'),
  (251, 'Doscientos cincuenta y uno', '251 días de actividad', 'IconCalendar', '#3B82F6'),
  (252, 'Doscientos cincuenta y dos', 'Completa 252 hábitos en total', 'IconTarget', '#EF4444'),
  (253, 'Doscientos cincuenta y tres', '253 días de racha', 'IconFlame', '#EF4444'),
  (254, 'Doscientos cincuenta y cuatro', 'Alcanza nivel 254', 'IconCrown', '#FBBF24'),
  (255, 'Doscientos cincuenta y cinco', '255 días de actividad (8.5 meses)', 'IconCalendarMonth', '#7C3AED'),
  (256, 'Doscientos cincuenta y seis', '256 días de racha', 'IconFlame', '#EF4444'),
  (257, 'Doscientos cincuenta y siete', 'Acumula 2570 puntos', 'IconCoin', '#FBBF24'),
  (258, 'Doscientos cincuenta y ocho', '258 días de actividad (36.5 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (259, 'Doscientos cincuenta y nueve', '259 días de racha', 'IconFlame', '#EF4444'),
  (260, 'Doscientos sesenta', '260 días de actividad', 'IconCalendar', '#3B82F6'),
  (261, 'Doscientos sesenta y uno', '261 días de racha', 'IconFlame', '#EF4444'),
  (262, 'Doscientos sesenta y dos', 'Completa 262 hábitos en total', 'IconTarget', '#EF4444'),
  (263, 'Doscientos sesenta y tres', '263 días de actividad', 'IconCalendar', '#3B82F6'),
  (264, 'Doscientos sesenta y cuatro', 'Alcanza nivel 264', 'IconCrown', '#FBBF24'),
  (265, 'Doscientos sesenta y cinco', '265 días de racha', 'IconFlame', '#EF4444'),
  (266, 'Doscientos sesenta y seis', '266 días de actividad', 'IconCalendar', '#3B82F6'),
  (267, 'Doscientos sesenta y siete', 'Acumula 2670 puntos', 'IconCoin', '#FBBF24'),
  (268, 'Doscientos sesenta y ocho', '268 días de racha (38 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (269, 'Doscientos sesenta y nueve', '269 días de actividad', 'IconCalendar', '#3B82F6'),
  (270, 'Nueve meses', '270 días de racha (9 meses)', 'IconCalendarMonth', '#7C3AED'),
  (271, 'Doscientos setenta y uno', '271 días de actividad', 'IconCalendar', '#3B82F6'),
  (272, 'Doscientos setenta y dos', 'Completa 272 hábitos en total', 'IconTarget', '#EF4444'),
  (273, 'Doscientos setenta y tres', '273 días de racha', 'IconFlame', '#EF4444'),
  (274, 'Doscientos setenta y cuatro', 'Alcanza nivel 274', 'IconCrown', '#FBBF24'),
  (275, 'Doscientos setenta y cinco', '275 días de actividad', 'IconCalendar', '#3B82F6'),
  (276, 'Doscientos setenta y seis', '276 días de racha', 'IconFlame', '#EF4444'),
  (277, 'Doscientos setenta y siete', 'Acumula 2770 puntos', 'IconCoin', '#FBBF24'),
  (278, 'Doscientos setenta y ocho', '278 días de actividad', 'IconCalendar', '#3B82F6'),
  (279, 'Doscientos setenta y nueve', '279 días de racha', 'IconFlame', '#EF4444'),
  (280, 'Doscientos ochenta', '280 días de racha (40 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (281, 'Doscientos ochenta y uno', '281 días de actividad', 'IconCalendar', '#3B82F6'),
  (282, 'Doscientos ochenta y dos', 'Completa 282 hábitos en total', 'IconTarget', '#EF4444'),
  (283, 'Doscientos ochenta y tres', '283 días de racha', 'IconFlame', '#EF4444'),
  (284, 'Doscientos ochenta y cuatro', 'Alcanza nivel 284', 'IconCrown', '#FBBF24'),
  (285, 'Doscientos ochenta y cinco', '285 días de actividad (9.5 meses)', 'IconCalendarMonth', '#7C3AED'),
  (286, 'Doscientos ochenta y seis', '286 días de racha', 'IconFlame', '#EF4444'),
  (287, 'Doscientos ochenta y siete', 'Acumula 2870 puntos', 'IconCoin', '#FBBF24'),
  (288, 'Doscientos ochenta y ocho', '288 días de actividad', 'IconCalendar', '#3B82F6'),
  (289, 'Doscientos ochenta y nueve', '289 días de racha', 'IconFlame', '#EF4444'),
  (290, 'Doscientos noventa', '290 días de actividad', 'IconCalendar', '#3B82F6'),
  (291, 'Doscientos noventa y uno', '291 días de racha', 'IconFlame', '#EF4444'),
  (292, 'Doscientos noventa y dos', 'Completa 292 hábitos en total', 'IconTarget', '#EF4444'),
  (293, 'Doscientos noventa y tres', '293 días de actividad', 'IconCalendar', '#3B82F6'),
  (294, 'Doscientos noventa y cuatro', 'Alcanza nivel 294', 'IconCrown', '#FBBF24'),
  (295, 'Doscientos noventa y cinco', '295 días de racha', 'IconFlame', '#EF4444'),
  (296, 'Doscientos noventa y seis', '296 días de actividad', 'IconCalendar', '#3B82F6'),
  (297, 'Doscientos noventa y siete', 'Acumula 2970 puntos', 'IconCoin', '#FBBF24'),
  (298, 'Doscientos noventa y ocho', '298 días de racha (42.5 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (299, 'Doscientos noventa y nueve', '299 días de actividad', 'IconCalendar', '#3B82F6'),
  (300, '¡Trescientos!', '300 días de racha consecutiva', 'IconTrophy', '#F59E0B'),
  (301, 'Trescientos uno', '301 días de actividad', 'IconCalendar', '#3B82F6'),
  (302, 'Trescientos dos', 'Completa 302 hábitos en total', 'IconTarget', '#EF4444'),
  (303, 'Trescientos tres', '303 días de racha', 'IconFlame', '#EF4444'),
  (304, 'Trescientos cuatro', 'Alcanza nivel 304', 'IconCrown', '#FBBF24'),
  (305, 'Trescientos cinco', '305 días de actividad (10 meses)', 'IconCalendarMonth', '#7C3AED'),
  (306, 'Trescientos seis', '306 días de racha (43.5 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (307, 'Trescientos siete', 'Acumula 3070 puntos', 'IconCoin', '#FBBF24'),
  (308, 'Trescientos ocho', '308 días de actividad', 'IconCalendar', '#3B82F6'),
  (309, 'Trescientos nueve', '309 días de racha', 'IconFlame', '#EF4444'),
  (310, 'Trescientos diez', '310 días de actividad', 'IconCalendar', '#3B82F6'),
  (311, 'Trescientos once', '311 días de racha', 'IconFlame', '#EF4444'),
  (312, 'Trescientos doce', 'Completa 312 hábitos en total', 'IconTarget', '#EF4444'),
  (313, 'Trescientos trece', '313 días de actividad', 'IconCalendar', '#3B82F6'),
  (314, 'Trescientos catorce', 'Alcanza nivel 314', 'IconCrown', '#FBBF24'),
  (315, 'Trescientos quince', '315 días de racha (10.5 meses)', 'IconCalendarMonth', '#7C3AED'),
  (316, 'Trescientos dieciséis', '316 días de actividad', 'IconCalendar', '#3B82F6'),
  (317, 'Trescientos diecisiete', 'Acumula 3170 puntos', 'IconCoin', '#FBBF24'),
  (318, 'Trescientos dieciocho', '318 días de racha (45.5 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (319, 'Trescientos diecinueve', '319 días de actividad', 'IconCalendar', '#3B82F6'),
  (320, 'Trescientos veinte', '320 días de racha', 'IconFlame', '#EF4444'),
  (321, 'Trescientos veintiuno', '321 días de actividad', 'IconCalendar', '#3B82F6'),
  (322, 'Trescientos veintidós', 'Completa 322 hábitos en total', 'IconTarget', '#EF4444'),
  (323, 'Trescientos veintitrés', '323 días de racha', 'IconFlame', '#EF4444'),
  (324, 'Trescientos veinticuatro', 'Alcanza nivel 324', 'IconCrown', '#FBBF24'),
  (325, 'Trescientos veinticinco', '325 días de actividad', 'IconCalendar', '#3B82F6'),
  (326, 'Trescientos veintiséis', '326 días de racha', 'IconFlame', '#EF4444'),
  (327, 'Trescientos veintisiete', 'Acumula 3270 puntos', 'IconCoin', '#FBBF24'),
  (328, 'Trescientos veintiocho', '328 días de actividad (47 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (329, 'Trescientos veintinueve', '329 días de racha', 'IconFlame', '#EF4444'),
  (330, 'Trescientos treinta', '330 días de racha (11 meses)', 'IconCalendarMonth', '#7C3AED'),
  (331, 'Trescientos treinta y uno', '331 días de actividad', 'IconCalendar', '#3B82F6'),
  (332, 'Trescientos treinta y dos', 'Completa 332 hábitos en total', 'IconTarget', '#EF4444'),
  (333, 'Trescientos treinta y tres', '333 días de racha', 'IconFlame', '#EF4444'),
  (334, 'Trescientos treinta y cuatro', 'Alcanza nivel 334', 'IconCrown', '#FBBF24'),
  (335, 'Trescientos treinta y cinco', '335 días de actividad', 'IconCalendar', '#3B82F6'),
  (336, 'Trescientos treinta y seis', '336 días de racha (48 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (337, 'Trescientos treinta y siete', 'Acumula 3370 puntos', 'IconCoin', '#FBBF24'),
  (338, 'Trescientos treinta y ocho', '338 días de actividad', 'IconCalendar', '#3B82F6'),
  (339, 'Trescientos treinta y nueve', '339 días de racha', 'IconFlame', '#EF4444'),
  (340, 'Trescientos cuarenta', '340 días de actividad', 'IconCalendar', '#3B82F6'),
  (341, 'Trescientos cuarenta y uno', '341 días de racha', 'IconFlame', '#EF4444'),
  (342, 'Trescientos cuarenta y dos', 'Completa 342 hábitos en total', 'IconTarget', '#EF4444'),
  (343, 'Trescientos cuarenta y tres', '343 días de actividad', 'IconCalendar', '#3B82F6'),
  (344, 'Trescientos cuarenta y cuatro', 'Alcanza nivel 344', 'IconCrown', '#FBBF24'),
  (345, 'Trescientos cuarenta y cinco', '345 días de racha (11.5 meses)', 'IconCalendarMonth', '#7C3AED'),
  (346, 'Trescientos cuarenta y seis', '346 días de actividad', 'IconCalendar', '#3B82F6'),
  (347, 'Trescientos cuarenta y siete', 'Acumula 3470 puntos', 'IconCoin', '#FBBF24'),
  (348, 'Trescientos cuarenta y ocho', '348 días de racha (49.5 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (349, 'Trescientos cuarenta y nueve', '349 días de actividad', 'IconCalendar', '#3B82F6'),
  (350, 'Trescientos cincuenta', '350 días de racha', 'IconFlame', '#EF4444'),
  (351, 'Trescientos cincuenta y uno', '351 días de actividad', 'IconCalendar', '#3B82F6'),
  (352, 'Trescientos cincuenta y dos', 'Completa 352 hábitos en total', 'IconTarget', '#EF4444'),
  (353, 'Trescientos cincuenta y tres', '353 días de racha', 'IconFlame', '#EF4444'),
  (354, 'Trescientos cincuenta y cuatro', 'Alcanza nivel 354', 'IconCrown', '#FBBF24'),
  (355, 'Trescientos cincuenta y cinco', '355 días de actividad', 'IconCalendar', '#3B82F6'),
  (356, 'Trescientos cincuenta y seis', '356 días de racha (51 semanas)', 'IconCalendarWeek', '#7C3AED'),
  (357, 'Trescientos cincuenta y siete', 'Acumula 3570 puntos', 'IconCoin', '#FBBF24'),
  (358, 'Trescientos cincuenta y ocho', '358 días de actividad', 'IconCalendar', '#3B82F6'),
  (359, 'Trescientos cincuenta y nueve', '359 días de racha', 'IconFlame', '#EF4444'),
  (360, '¡Un año completo!', '360 días de racha (12 meses)', 'IconCalendarMonth', '#7C3AED'),
  (361, 'Trescientos sesenta y uno', '361 días de actividad', 'IconCalendar', '#3B82F6'),
  (362, 'Trescientos sesenta y dos', 'Completa 362 hábitos en total', 'IconTarget', '#EF4444'),
  (363, 'Trescientos sesenta y tres', '363 días de racha', 'IconFlame', '#EF4444'),
  (364, 'Trescientos sesenta y cuatro', 'Alcanza nivel 364', 'IconCrown', '#FBBF24'),
  (365, '¡Leyenda absoluta!', '365 días de racha — ¡un año entero!', 'IconCrown', '#FBBF24')
ON CONFLICT (day_of_year) DO NOTHING;
